#!/usr/bin/env python3
"""Deterministic self-check for ghostwrite outputs.

Usage:
    python skills/ghostwrite/lint.py <path-to-draft.md>

Exit 0 = clean. Exit 1 = findings (one per line on stdout as "FAIL: <rule>: <evidence>").
No dependencies beyond the stdlib.
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

# Banned phrases / words — sourced from skills/ghostwrite/SKILL.md "What to Avoid"
# and the AI-tell checklist. Case-insensitive whole-word matches.
BANNED_PATTERNS: list[tuple[str, str]] = [
    (r"\bexcited to share\b", "excited to share"),
    (r"\bleverage[ds]?\b", "'leverage' (verb)"),
    (r"\becosystem\b", "ecosystem"),
    (r"\bdelve[ds]?\b", "delve"),
    (r"\bsynergy\b", "synergy"),
    (r"\bgame[- ]changer\b", "game-changer"),
    (r"\bparadigm shift\b", "paradigm shift"),
    (r"\babsolutely incredible\b", "absolutely incredible"),
    (r"Let me know in the comments", "engagement-bait closer"),
]

AI_ATTRIBUTION_PATTERNS: list[tuple[str, str]] = [
    (r"Generated with \[?Claude", "'Generated with Claude' attribution"),
    (r"Co-Authored-By:\s*Claude", "'Co-Authored-By: Claude' trailer"),
    (r"\bAI-assisted\b", "'AI-assisted' marker"),
    (r"\bGenerated by Claude\b", "'Generated by Claude' marker"),
    (r"🤖\s*Generated", "robot-emoji Generated marker"),
]


def check_no_em_dash(text: str) -> str | None:
    if "—" in text:
        idx = text.index("—")
        ctx = text[max(0, idx - 20) : idx + 20].replace("\n", " ")
        return f"em dash found: ...{ctx}..."
    return None


def check_banned_phrases(text: str) -> list[str]:
    findings: list[str] = []
    for pat, label in BANNED_PATTERNS:
        if re.search(pat, text, re.IGNORECASE):
            findings.append(f"banned phrase: {label}")
    return findings


def check_ai_attribution(text: str) -> list[str]:
    findings: list[str] = []
    for pat, label in AI_ATTRIBUTION_PATTERNS:
        if re.search(pat, text):
            findings.append(f"AI attribution: {label}")
    return findings


def lint(text: str) -> list[str]:
    findings: list[str] = []
    em = check_no_em_dash(text)
    if em:
        findings.append(f"FAIL: no_em_dash: {em}")
    for f in check_banned_phrases(text):
        findings.append(f"FAIL: banned_phrases: {f}")
    for f in check_ai_attribution(text):
        findings.append(f"FAIL: no_ai_attribution: {f}")
    return findings


def main(argv: list[str]) -> int:
    if len(argv) != 2:
        print("usage: python skills/ghostwrite/lint.py <path>", file=sys.stderr)
        return 2
    path = Path(argv[1])
    if not path.exists():
        print(f"FAIL: file not found: {path}")
        return 1
    text = path.read_text()
    findings = lint(text)
    for f in findings:
        print(f)
    return 1 if findings else 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
